# Generated by Django 3.1 on 2020-08-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direction',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
